### PR TITLE
Fix for headers field_to_match #94

### PR DESCRIPTION
**Pull request by MatanHeledPort**
# Description

Lookup for `field_to_match` in `headers` wasn't scanning keys.
This should fix the issue #94 

Please explain the changes you made here and link to any relevant issues.
Changed :
`lookup(match_pattern.value, "all", {}`
to:
`lookup(keys(match_pattern.value), "all", {}`

### CODE REVIEW

**Comment by felipe88alves** [comment]
Only suggestion would be to remove the not statement from the example to keep the scope of the test simpler, not a blocker from merging anyways.

In any case , I can't approve but `lgtm`

**Review by felipe88alves — APPROVED** [review]

**Review by felipe88alves — APPROVED** [review]
lgtm

**Comment by MatanHeledPort** [comment]
@Ohid25 Would appreciate a review here (:

**Review by Ohid25 — APPROVED** [review]
LGTM 🎉

**Comment by Ohid25** [comment]
Thank you for your contribution! This is now released as a part of [4.4.0](https://github.com/umotif-public/terraform-aws-waf-webaclv2/releases/tag/4.4.0).

**Pull request merged**
